doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'

        types:
            race_id: App\RaceCatalog\Infrastructure\Persistence\Doctrine\Type\RaceIdType
            edition_id: App\RaceCatalog\Infrastructure\Persistence\Doctrine\Type\EditionIdType
            distance_id: App\RaceCatalog\Infrastructure\Persistence\Doctrine\Type\DistanceIdType
            user_id: App\UserProfile\Infrastructure\Persistence\Doctrine\Type\UserIdType
            watchlist_entry_id: App\UserProfile\Infrastructure\Persistence\Doctrine\Type\WatchlistEntryIdType

    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            RaceCatalog:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/RaceCatalog/Infrastructure/Persistence/Mapping'
                prefix: 'App\RaceCatalog\Domain\Model'
                alias: RaceCatalog
            UserProfile:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/UserProfile/Infrastructure/Persistence/Mapping'
                prefix: 'App\UserProfile\Domain\Model'
                alias: UserProfile

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
