<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260427163955 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE race_catalog_distances (name VARCHAR(255) NOT NULL, length_in_km DOUBLE PRECISION NOT NULL, price_in_pln DOUBLE PRECISION DEFAULT NULL, id VARCHAR(36) NOT NULL, edition_id VARCHAR(36) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9429BFF474281A5E ON race_catalog_distances (edition_id)');
        $this->addSql('CREATE TABLE race_catalog_editions (date DATE NOT NULL, registration_url VARCHAR(2048) DEFAULT NULL, id VARCHAR(36) NOT NULL, race_id VARCHAR(36) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C8D2C9BB6E59D40D ON race_catalog_editions (race_id)');
        $this->addSql('CREATE TABLE race_catalog_races (name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, voivodeship VARCHAR(100) NOT NULL, country VARCHAR(2) NOT NULL, id VARCHAR(36) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A491284F989D9B62 ON race_catalog_races (slug)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE race_catalog_distances ADD CONSTRAINT FK_9429BFF474281A5E FOREIGN KEY (edition_id) REFERENCES race_catalog_editions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE race_catalog_editions ADD CONSTRAINT FK_C8D2C9BB6E59D40D FOREIGN KEY (race_id) REFERENCES race_catalog_races (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE race_catalog_distances DROP CONSTRAINT FK_9429BFF474281A5E');
        $this->addSql('ALTER TABLE race_catalog_editions DROP CONSTRAINT FK_C8D2C9BB6E59D40D');
        $this->addSql('DROP TABLE race_catalog_distances');
        $this->addSql('DROP TABLE race_catalog_editions');
        $this->addSql('DROP TABLE race_catalog_races');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
