services:
  _defaults:
    public: true

  App\RaceCatalog\Domain\Repository\RaceRepositoryInterface:
    alias: App\RaceCatalog\Infrastructure\Persistence\Doctrine\Repository\DoctrineRaceRepository
    public: true

  App\UserProfile\Domain\Repository\UserRepositoryInterface:
    alias: App\UserProfile\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository
    public: true

  App\UserProfile\Domain\Repository\WatchlistEntryRepositoryInterface:
    alias: App\UserProfile\Infrastructure\Persistence\Doctrine\Repository\DoctrineWatchlistEntryRepository

  App\Review\Domain\Repository\ReviewRepositoryInterface:
    alias: App\Review\Infrastructure\Persistence\Doctrine\Repository\DoctrineReviewRepository